### ISSUE TITLE
Use units in sigma tau assignment

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm#11]
@chfleming @jmcalabrese 

Currently assign a value in `sigma`, `tau` etc require unit conversion manually, especially when you read the value from variogram, then need to convert to SI units.

```r
m0 <- ctmm(sigma=23*1000^2) # 23 km^2 in m^2
m1 <- ctmm(sigma=23*1000^2,tau=6*24*60^2) # and 6 days in seconds
```

How about we make a utility function that take format like `23 km2`, `6 days`? With some simple rules these kind of input can be converted to SI unit value. So it will look like

```r
m0 <- ctmm(sigma=SI("23 km^2")) 
m1 <- ctmm(sigma=SI("23 km^2"),tau=SI("6 days")) 
```

It should also take vector input so this

```r
dt <- 60*60*c(1,5,25)
SVF3 <- variogram(gazelle[[18]],dt=dt)
```

become

```r
SVF3 <- variogram(gazelle[[18]],dt=SI("1 5 25 hours"))
```

**Comment by chfleming** [comment]
I actually have code written to do that. I just need to export it in the NAMESPACE and document it. I will move it up on the TODO list.

**Comment by xhdong-umd** [comment]
That will be great. I think users will find it more friendly to use.

**Comment by chfleming** [comment]
Exported, documented, and vignettes updated.

[Here is the example.](https://ctmm-initiative.github.io/ctmm/reference/unit.html#examples)
