### ISSUE TITLE
minor issue with help page of `unit`

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm#13]
I cannot view the help page of `unit` properly.

```
> ?ctmm:::unit
No documentation for ‘unit’ in specified packages and libraries:
you could try ‘??unit’
> ??unit
```
This found this page
<img width="310" alt="screen shot 2017-08-03 at 11 55 35 am" src="https://user-images.githubusercontent.com/25039897/28931013-b1943018-7842-11e7-80c2-c2f3959853b0.png">

but clicking it get this error
```
Only help files, NEWS, DESCRIPTION and files under doc/ and demo/ in a package can be viewed
```

If I click through the package help index, it can be showed properly

<img width="669" alt="screen shot 2017-08-03 at 11 57 15 am" src="https://user-images.githubusercontent.com/25039897/28931080-f0b312fa-7842-11e7-91ca-f74a2c1c5086.png">

**Comment by chfleming** [comment]
I didn't export `unit` in `NAMESPACE` but only the binary operator `%#%`. I have no idea why the help file works from the package listing and not the search page.

**Comment by chfleming** [comment]
@xhdong-umd 
Both `help("%#%")` and clicking on the link to `%#%` in the package listing work for me now in R 3.4.1 and ctmm 0.4.0.
