### ISSUE TITLE
Possible source of confusion in Occurrence help page

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmm#14]
@chfleming 

In the Help page of "Calculate a Kriged occurrence disribution estimate", you use "UD" in the example. Would it help the users not confuse the occurence distribution with e.g. akde or bb UD, if you wrote "OD" instead of UD?

Examples

# Load package and data
library(ctmm)
data(buffalo)
Cilla <- buffalo$Cilla

GUESS <- ctmm.guess(Cilla,interactive=FALSE)
FIT <- ctmm.fit(Cilla,GUESS)

# Compute occurence distribution
UD <- occurrence(Cilla,FIT)

# Plot occurrence UD
plot(UD,col.level=NA)

**Comment by chfleming** [comment]
The BB UD is also an occurrence distribution though, which you can calculate with this function.

In our papers, we've been using UD as the generic term for either a range (AKDE) or occurrence distribution (BB, Krige).
