### ISSUE TITLE
Consider caching expensive calculations with `memoise`?

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm#15]
There are some calculations in `ctmm` that take some time. In my experiments and tests I often need to run some code repetitively. I found caching them with [`memoise`](https://github.com/r-lib/memoise) can save a lot of time.

I'm wondering if `ctmm` in general can adopt it. For example, you can create a cache folder under `inst`, and all repeat calculations with same parameters will get instant result.

**Comment by chfleming** [comment]
I'm not sure that I can see the benefit of this functionality on the command line?

**Comment by xhdong-umd** [comment]
For end user may not be obvious. I remember that when I played with the package website generator for `ctmm`, I need to compile some vignettes again and again in experimenting some scripts. Having those calculations cached could save some time.

Though if you don't have this kind of usage then it would not help.

**Comment by chfleming** [comment]
I think there is some cache functionality in the vignettes (in knitr) that I have not been using.

**Comment by xhdong-umd** [comment]
Yes I looked at that before and never used it. It looks a little bit complicated and not as flexible as memoise.
