### ISSUE TITLE
Argument for raster cell size

### ISSUE THREAD

**Issue by kjklauder** [ctmm-initiative/ctmm#17]
It would be great to have an argument in the writeRaster command that would dictate the cell size of the raster. This would improve applicability and facilitate consistency between exports.

**Comment by chfleming** [comment]
I can put this on the TODO list. The grid specifications will have to be made before `writeRaster()`, in `adke()` though.

**Comment by chfleming** [comment]
The `akde()` and `occurrence()` methods now support a `grid` argument, which can be used to set the cell size. See `help('akde')`.
