### ISSUE TITLE
units of summary on models

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm#21]
My model summary table rely on the summary on model with `units = FALSE`, so I can convert the values by proper units. 

I noticed the current version of ctmm is reporting with much smaller units, and I was assuming SI units, so my result is off a lot.

```r
> summary(model_try_res[[1]][[1]])
$DOF
    mean     area 
16.34829 31.36117 

$CI
                                low         ML       high
area (square kilometers) 258.930587 380.155725 524.290131
tau position (days)        2.811414   4.740313   7.992622

> summary(model_try_res[[1]][[1]], units = FALSE)
$DOF
    mean     area 
16.34829 31.36117 

$CI
                                     low           ML         high
area (square microns)       2.589306e+20 3.801557e+20 5.242901e+20
tau position (microseconds) 2.429062e+11 4.095631e+11 6.905626e+11
```

**Comment by chfleming** [comment]
The unintended consequences of new features...

**Comment by chfleming** [comment]
Sorry to take so long. I was in the middle of another bit of coding. This should be fixed now. I added an `SI=FALSE` argument to the `ctmm:::unit()` function instead of using `threshhold=Inf`, which only worked when meters and seconds were the smallest supported units.
