### ISSUE TITLE
as.telemetry import error on some data

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm#22]
Today I found this error in importing telemetry data.

```r
> library(ctmm)
> tele <- as.telemetry("/Users/xhdong/Projects/ctmm-Shiny/data/misc tele/Movebank 1764627 - Kruger African Buffalo  GPS tracking  South Africa.csv")
Error in `[.data.frame`(DATA, , COL) : undefined columns selected
In addition: Warning message:
In as.telemetry.data.frame(data, timeformat = timeformat, timezone = timezone,  :
  No MoveBank identification found. Assuming data corresponds to one indiviudal.
```

The data is downloaded from movebank. [Here is a copy](https://drive.google.com/file/d/1GUopUScb0YqoqxiCt5pmOMj4LpI_kIAj/view?usp=sharing). I think there is animal id column in the data but not recognized.

In previous version of ctmm the same data can be imported properly.

```
timestamp,location_lat,location_long,individual_id,tag_id
2005-02-17 05:05:00.000,-24.53730062,31.76642049,1764819,197990562
2005-02-17 06:08:00.000,-24.53931071,31.76442057,1764819,197990562
2005-02-17 07:05:00.000,-24.54798991,31.76114095,1764819,197990562
2005-02-17 08:05:00.000,-24.54702962,31.76079915,1764819,197990562
```

**Comment by chfleming** [comment]
I'm not getting this behavior with the master branch of `ctmm` on that data.

**Comment by xhdong-umd** [comment]
With CRAN ctmm it's normal

```r
> library(ctmm)
> tele <- as.telemetry("/Users/xhdong/Projects/ctmm-Shiny/data/misc tele/Movebank 1764627 - Kruger African Buffalo  GPS tracking  South Africa.csv")
Minimum sampling interval of 0 seconds in 197990562
Minimum sampling interval of 2 minutes in 197990566
Minimum sampling interval of 3 minutes in 197990568
Minimum sampling interval of 2 minutes in 197990570
Minimum sampling interval of 0 seconds in 197990572
Minimum sampling interval of 3 minutes in 197990574
Minimum sampling interval of 0 seconds in 197990576
Warning messages:
1: In telemetry.clean(telist[[i]], id = id[i]) :
  Duplicate times in 197990562. Data cannot be fit without an error model.
2: In telemetry.clean(telist[[i]], id = id[i]) :
  Times might be out of order or duplicated in 197990566. Make sure that timeformat and timezone are correctly specified.
3: In telemetry.clean(telist[[i]], id = id[i]) :
  Times might be out of order or duplicated in 197990572. Make sure that timeformat and timezone are correctly specified.
4: In telemetry.clean(telist[[i]], id = id[i]) :
  Duplicate times in 197990572. Data cannot be fit without an error model.
5: In telemetry.clean(telist[[i]], id = id[i]) :
  Times might be out of order or duplicated in 197990576. Make sure that timeformat and timezone are correctly specified.
6: In telemetry.clean(telist[[i]], id = id[i]) :
  Duplicate times in 197990576. Data cannot be fit without an error model.
```

With current master branch

```r
> devtools::install_github("ctmm-initiative/ctmm")
Downloading GitHub repo ctmm-initiative/ctmm@master
from URL https://api.github.com/repos/ctmm-initiative/ctmm/zipball/master
Installing ctmm
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/f3/6cdx4zf94qz95r6d89s_4xcsrcsjqm/T/RtmpfHEvnp/devtools9edf57ca79c8/ctmm-initiative-ctmm-26a887e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 

* installing *source* package ‘ctmm’ ...
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (ctmm)
> library(ctmm)
> tele <- as.telemetry("/Users/xhdong/Projects/ctmm-Shiny/data/misc tele/Movebank 1764627 - Kruger African Buffalo  GPS tracking  South Africa.csv")
Error in `[.data.frame`(DATA, , COL) : undefined columns selected
In addition: Warning message:
In as.telemetry.data.frame(data, timeformat = timeformat, timezone = timezone,  :
  No MoveBank identification found. Assuming data corresponds to one indiviudal.
```

I'm using R 3.5.0 and data.table 1.11.4 cran version.

**Comment by chfleming** [comment]
The file you linked has a different name and more columns, including the animal's names.

**Comment by chfleming** [comment]
Can you link to the other data? `tag_id` should have worked in the master branch.

**Comment by xhdong-umd** [comment]
I linked the same file I used above. 

https://drive.google.com/file/d/1df0cmsDoDjzsWyzmCoEvmEkMbYQRW4MD/view?usp=sharing

**Comment by chfleming** [comment]
Looks like I made some embarrassing updates to `pull.column`... to the point where I'm not sure how anything was working.

I made a fix and am running check now. Will be up in a few hours, after I get back from dinner.

**Comment by chfleming** [comment]
This and related bugs should be fixed now.

**Comment by bjpadilla** [comment]
> This and related bugs should be fixed now.

Hello. 

I see that the bug was reported as fixed in 2018. But, when re-analyzing some data with identical R script and data set I am again getting this same error. 

`## Both 2018 AND 2019  ####
> trk <- make_track(etib,Longitude..deg.,Latitude..deg.,  # All years (2018 and 2019)
+                   date_time, id = Collar.ID,year = year, month = month,sex=sex,season = seas, crs = crs(sgl), sex = sex) %>%  
+   transform_coords(crs(trug))
.t found, creating `track_xyt`.
> elks <- trk %>% nest(data = -c(id, year,season)) %>% 
+   mutate(n = map_int(data, nrow)) %>% 
+   filter(n > 20)
> elks1 <- elks %>%
+   mutate(
+     "hr_od_ou" = map(data, ~ hr_od(., model = fit_ctmm(., "ou"))),
+     "hr_od_50" = map(data, ~ hr_od(., model = fit_ctmm(., "ou"), levels = c(0.5)))
+   )
Minimum sampling interval of 4.46 hours in unknown
Error: Problem with `mutate()` input `hr_od_ou`.
x NA
ℹ Input `hr_od_ou` is `map(data, ~hr_od(., model = fit_ctmm(., "ou")))`.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning messages:
1: Problem with `mutate()` input `hr_od_ou`.
ℹ No MoveBank identification found. Assuming data corresponds to one indiviudal.
ℹ Input `hr_od_ou` is `map(data, ~hr_od(., model = fit_ctmm(., "ou")))`. 
2: In as.telemetry.data.frame(data.frame(lon = x$x_, lat = x$y_, timestamp = x$t_)) :
  No MoveBank identification found. Assuming data corresponds to one indiviudal.`
