### ISSUE TITLE
Inconsistent output from ctmm.select()

### ISSUE THREAD

**Issue by padpadpadpad** [ctmm-initiative/ctmm#38]
I have been helping a student with some models and came across something inconsistent in how models are assigned in the `summary()` output of a `ctmm.select()` object. The models are identical and the AICc scores are identical, but the order of the models is different...

The student wanted to use a loop to write several objects to the environment so we were using `assign()` and then `get(data)` inside the `cttm.select()` call. However the problem remains even in a simple reproducible example.

Having ran different variations of the code, it appears to be something wrong with running `ctmm.select()` inside `assign()`, but I cannot understand what the problem is.

```r
# test code
library(ctmm)

data(buffalo)
Cilla <- buffalo$Cilla
vario.cilla<-variogram(Cilla)

GUESS <- ctmm.guess(Cilla, variogram = vario.cilla, interactive=FALSE)

# The four lines of code below should work the same 
FIT <- ctmm.select(Cilla,CTMM=GUESS, verbose=TRUE)
assign(paste("FIT", '1', sep = ""), ctmm.select(get('Cilla'),CTMM=GUESS, verbose=TRUE))
FIT2 <- ctmm.select(get('Cilla'),CTMM=GUESS, verbose=TRUE)
assign(paste("FIT", '3', sep = ""), ctmm.select(Cilla ,CTMM=GUESS, verbose=TRUE))

# check
summary(FIT)
summary(FIT1)
summary(FIT2)
summary(FIT3)
```

The summary output is:
![Screen Shot 2020-10-27 at 17 03 38](https://user-images.githubusercontent.com/10220722/97336240-b1047900-1876-11eb-9e03-218fff1c16f5.png)

The two assign() outputs have a different order to the ones using `<-`. Any idea why this might be?

Many thanks
Dan

**Comment by chfleming** [comment]
Thanks for raising the issue. It should be fixed in the master branch now.

The list names were not being updated because of an oversight. The actual objects were fine and in order. They were just mislabeled in the list.
