### ISSUE TITLE
Graphical representation and shape file of bootstrapped akde

### ISSUE THREAD

**Issue by tdokhelar** [ctmm-initiative/ctmm#40]
Hello,

Is there is a way to obtain both a graphical representation and to write a shape file from a bootstrapped akde object ?

Both these function seems to do not support bootstrapped object.
Indeed, the plot function runs without error but gives me an empty plot and I'm getting this error message whenever I try to run the differents writeShapeFile functions : 
` Error in seq.default(0, 1, length.out = ncol(z)) : argument 'length.out' must be of length 1 `

Thanks in advance !

**Comment by chfleming** [comment]
How are you calling this function? I just tested `ctmm.boot()` and am not getting any issues with plotting the resulting AKDEs. It should be used to improve the output of `ctmm.fit()` or `ctmm.select()`, and then fed into `akde()` as you would any other model fit object. I can add an example to associated help file.

**Comment by tdokhelar** [comment]
Thanks for your help ! I was trying to use directly the bootstrapped object into the plot and writeShapeFile functions without putting it in the ctmm.fit function !
