### ISSUE TITLE
Use of overlap function with vectors

### ISSUE THREAD

**Issue by Kasi21** [ctmm-initiative/ctmm#41]
Hello, 

I would like to generate confidence intervals for the BA Coefficient for two vectors (that represent activity curves of detection counts - I do not want to model the probability distribution functions). 

Is it possible to use the overlap function in ctmm to compute the BA coefficient and the associated confidence intervals for these two vectors ?

Alternatively, do you know of how else to generate a confidence interval for the BA coefficient in my case (I am able to generate the BA coefficient with a custom function).

I know that this use case is not movement related, but I was wondering if ctmm would still be suitable for my need.

Thank you in advance, 

Kasim

**Comment by chfleming** [comment]
The BA calculation in ctmm is coded for either 2D Gaussian distributions or 2D rasterized distributions, so it won't work in other cases, as coded.

Additionally, I don't know the meaning of the Bhattacharyya affinity outside of some kind of distribution. So you could calculate the BA for two activity distributions, if you had the probability of each activity as a function of time. The point estimate for that seems pretty straightforward, and would be overlap as a function of time. But I'm not familiar enough with this kind of data to know what the uncertainty would be to propagate it.

**Comment by Kasi21** [comment]
That's useful to know. Thank you for your reply - I will look at some other options. 

All the best
