### ISSUE TITLE
interactive = TRUE

### ISSUE THREAD

**Issue by MarkJThomas** [ctmm-initiative/ctmm#44]
Hi, when I run:

`GUESS<-ctmm.guess(OCT$OC1,CTMM = FITS4$OC1, interactive = TRUE)`

the plot is not interactive

I tried loading library(manipulate) but still not working, not sure if it's an issue or my R studio

TIA

**Comment by MarkJThomas** [comment]
When I run:

`library(manipulate)
manipulate(plot(1:x), x = slider(5, 10))`

before the above the gear icon appeared, then when I run 

`GUESS<-ctmm.guess(OCT$OC1,CTMM = FITS4$OC1, interactive = TRUE)`

it worked!

**Comment by chfleming** [comment]
Unfortunately, the `manipulate` library has become fairly unreliable in Rstudio. Sometimes if you call a `manipulate` function multiple times, then it will eventually start working. Other times it won't. The only solution I can really provide is an alternative `variogram.fit` output option like through RShiny.
