### ISSUE TITLE
Renaming inconsistent location classes in `tbind`

### ISSUE THREAD

**Issue by cwilhite4151** [ctmm-initiative/ctmm#50]
The `ubind` function called in `tbind` renames inconsistent location classes in lists of `telemetry` objects but only returns the combined `UERE` object to the `tbind` function and subsequently the renamed location classes are not returned from `tbind`.  `ubind` should return `x` with renamed classes to `tbind`.

Fix in `tbind`:
##
`    x <- ubind(x)`
`    UERE <- uere(x)`
##
Fix in `ubind`:
##
`    for (i in 1:length(x)) {`
`      x[[i]]@UERE <- UERE`
`    }`
`    return(x)`

**Comment by chfleming** [comment]
Thanks for the bug report and code suggestion. I've pushed a fix for this issue and added you as a contributor to the `DESCRIPTION` file.

**Comment by cwilhite4151** [comment]
Great, all fixed, thank you!
