### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [ctmm-initiative/ctmm#52]
@chfleming @xhdong-umd @kwinner: This package does not terminate its checks when run with the release candidate for igraph 2.0.0.

Is this a problem in your package? Should we be doing things differently?

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph")` .

We're planning to release igraph 2.0.0 on January 23. My sincere apologies for the short notice, I only realized today that I should have warned about the problem much earlier. Happy to postpone if it turns out that the problem is on our end. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by krlmlr** [comment]
Installing from r-universe might be easier: https://igraph.r-universe.dev/igraph# .

**Comment by chfleming** [comment]
Hi @krlmlr ,

If you re-compile the vignettes (`ctmm` vignettes use real data and are supplied pre-compiled) and you run the examples that are wrapped in `\donttest{}` then it takes a couple of hours to run a check on `ctmm`. Is that the issue here?

**Comment by krlmlr** [comment]
Maybe. The checks are just the regular `R CMD check` on the official tarball. How do your checks distinguish between CRAN and non-CRAN?

**Comment by chfleming** [comment]
As the maintainer, I run the full check. CRAN runs with `--no-vignettes`
[https://cran.r-project.org/web/checks/check_results_ctmm.html](https://cran.r-project.org/web/checks/check_results_ctmm.html)

**Comment by krlmlr** [comment]
That must be it, thanks.
